name: Tokemon
options:
  bundleIdPrefix: ai.tokemon
  deploymentTarget:
    macOS: "14.0"
  xcodeVersion: "15.0"
  generateEmptyDirectories: true
  minimumXcodeGenVersion: "2.40.0"

settings:
  base:
    SWIFT_VERSION: "6.0"
    MACOSX_DEPLOYMENT_TARGET: "14.0"
    PRODUCT_NAME: Tokemon
    MARKETING_VERSION: "1.0.0"
    CURRENT_PROJECT_VERSION: "1"

packages:
  MenuBarExtraAccess:
    url: https://github.com/orchetect/MenuBarExtraAccess.git
    from: "1.2.2"
  SettingsAccess:
    url: https://github.com/orchetect/SettingsAccess.git
    from: "2.1.0"
  KeychainAccess:
    url: https://github.com/kishikawakatsumi/KeychainAccess.git
    from: "4.2.2"

targets:
  Tokemon:
    type: application
    platform: macOS
    sources:
      - path: Tokemon
        excludes:
          - Info.plist
    resources:
      - path: Tokemon/Resources
        buildPhase: resources
    settings:
      base:
        INFOPLIST_FILE: Tokemon/Info.plist
        PRODUCT_BUNDLE_IDENTIFIER: ai.tokemon.app
        LD_RUNPATH_SEARCH_PATHS: "@executable_path/../Frameworks"
        COMBINE_HIDPI_IMAGES: YES
        ASSETCATALOG_COMPILER_APPICON_NAME: AppIcon
        CODE_SIGN_IDENTITY: "-"
        CODE_SIGN_STYLE: Automatic
        ENABLE_HARDENED_RUNTIME: YES
    dependencies:
      - package: MenuBarExtraAccess
      - package: SettingsAccess
      - package: KeychainAccess
    entitlements:
      path: Tokemon/Tokemon.entitlements
      properties:
        com.apple.security.app-sandbox: false

  TokemonTests:
    type: bundle.unit-test
    platform: macOS
    sources:
      - path: TokemonTests
    settings:
      base:
        PRODUCT_BUNDLE_IDENTIFIER: ai.tokemon.app.tests
        TEST_HOST: "$(BUILT_PRODUCTS_DIR)/Tokemon.app/Contents/MacOS/Tokemon"
        BUNDLE_LOADER: "$(TEST_HOST)"
        LD_RUNPATH_SEARCH_PATHS: "@executable_path/../Frameworks @loader_path/../Frameworks"
    dependencies:
      - target: Tokemon

  TokemonUITests:
    type: bundle.ui-testing
    platform: macOS
    sources:
      - path: TokemonUITests
    settings:
      base:
        PRODUCT_BUNDLE_IDENTIFIER: ai.tokemon.app.uitests
        TEST_TARGET_NAME: Tokemon
        LD_RUNPATH_SEARCH_PATHS: "@executable_path/../Frameworks @loader_path/../Frameworks"
    dependencies:
      - target: Tokemon

schemes:
  Tokemon:
    build:
      targets:
        Tokemon: all
        TokemonUITests: [test]
    run:
      config: Debug
      executable: Tokemon
    test:
      config: Debug
      gatherCoverageData: true
      targets:
        - TokemonTests
        - TokemonUITests
    profile:
      config: Release
    analyze:
      config: Debug
    archive:
      config: Release
