import SwiftUI

/// Self-contained SwiftUI view for PDF rendering.
/// CRITICAL: No @Environment dependencies. ImageRenderer creates an isolated rendering
/// context without the normal SwiftUI environment. All data must be passed as parameters.
struct PDFReportView: View {
    let accountName: String
    let generatedDate: Date
    let weeklySummaries: [UsageSummary]
    let monthlySummaries: [UsageSummary]
    let projectBreakdown: [ProjectUsage]
    let totalDataPoints: Int

    var body: some View {
        VStack(alignment: .leading, spacing: 12) {
            // 1. Header
            HStack(alignment: .top) {
                Text("ClaudeMon Usage Report")
                    .font(.title)
                    .fontWeight(.bold)
                    .foregroundStyle(.black)

                Spacer()

                Text(generatedDate, style: .date)
                    .font(.caption)
                    .foregroundStyle(.gray)
            }

            // 2. Account name
            Text(accountName)
                .font(.subheadline)
                .foregroundStyle(.black)

            // 3. Divider
            Rectangle()
                .fill(.gray.opacity(0.3))
                .frame(height: 1)

            // 4. Weekly Summary section
            if !weeklySummaries.isEmpty {
                Text("Weekly Summary")
                    .font(.headline)
                    .fontWeight(.semibold)
                    .foregroundStyle(.black)
                    .padding(.top, 4)

                ForEach(weeklySummaries) { summary in
                    HStack {
                        Text(summary.periodLabel)
                            .font(.callout)
                            .foregroundStyle(.black)
                        Spacer()
                        Text("Avg: \(String(format: "%.1f", summary.averageUtilization))%")
                            .font(.callout)
                            .foregroundStyle(.black)
                        Text("Peak: \(String(format: "%.1f", summary.peakUtilization))%")
                            .font(.callout)
                            .foregroundStyle(.black)
                            .frame(width: 100, alignment: .trailing)
                    }
                }
            }

            // 5. Monthly Summary section
            if !monthlySummaries.isEmpty {
                Text("Monthly Summary")
                    .font(.headline)
                    .fontWeight(.semibold)
                    .foregroundStyle(.black)
                    .padding(.top, 8)

                ForEach(monthlySummaries) { summary in
                    HStack {
                        Text(summary.periodLabel)
                            .font(.callout)
                            .foregroundStyle(.black)
                        Spacer()
                        Text("Avg: \(String(format: "%.1f", summary.averageUtilization))%")
                            .font(.callout)
                            .foregroundStyle(.black)
                        Text("Peak: \(String(format: "%.1f", summary.peakUtilization))%")
                            .font(.callout)
                            .foregroundStyle(.black)
                            .frame(width: 100, alignment: .trailing)
                    }
                }
            }

            // 6. Divider
            Rectangle()
                .fill(.gray.opacity(0.3))
                .frame(height: 1)
                .padding(.top, 4)

            // 7. Project Token Usage section (top 10)
            if !projectBreakdown.isEmpty {
                Text("Project Token Usage")
                    .font(.headline)
                    .fontWeight(.semibold)
                    .foregroundStyle(.black)
                    .padding(.top, 4)

                ForEach(Array(projectBreakdown.prefix(10))) { project in
                    HStack {
                        Text(project.projectName)
                            .font(.callout)
                            .foregroundStyle(.black)
                        Spacer()
                        Text(formatTokens(project.totalTokens))
                            .font(.callout)
                            .foregroundStyle(.black)
                    }
                }
            }

            // 8. Divider
            Rectangle()
                .fill(.gray.opacity(0.3))
                .frame(height: 1)
                .padding(.top, 4)

            // 9. Footer
            Spacer(minLength: 8)

            Text("Generated by ClaudeMon - https://claudemon.app")
                .font(.caption)
                .foregroundStyle(.gray)
                .frame(maxWidth: .infinity, alignment: .center)
        }
        .padding(24)
        .frame(width: 540)
        .background(.white)
    }

    // MARK: - Helpers

    /// Format token count: 1M+, 1K+, or raw number.
    private func formatTokens(_ count: Int) -> String {
        if count >= 1_000_000 {
            let millions = Double(count) / 1_000_000.0
            return String(format: "%.1fM tokens", millions)
        } else if count >= 1_000 {
            let thousands = Double(count) / 1_000.0
            return String(format: "%.1fK tokens", thousands)
        } else {
            return "\(count) tokens"
        }
    }
}
